### PR TITLE
Feature/10/add-expertise-section

### LINKED ISSUE #10: Add "Expertise" section

### PR DESCRIPTION
**Pull request by AmirAgassi**
💼[Add "Expertise" Section #10](https://github.com/KonferCA/landing/issues/10)

🔍 **What's Included**
- Created new `Expertise.tsx` section.
- Added images/descriptions for parties, conferences, networking, and seminars.
- Updated `Landing.tsx` to include `Expertise` section, replacing the old `About` section.

📁 Files Affected:
- `src/assets/expertise/conferences.png`
- `src/assets/expertise/networking.png`
- `src/assets/expertise/parties.png`
- `src/assets/expertise/seminars.png`
- `src/components/Expertise.tsx`
- `src/components/index.tsx`
- `src/pages/Landing.tsx`
- `src/index.css`
- `tailwind.config.js`

### CODE REVIEW

**Review by juancwu — DISMISSED** [review]

**Comment by aidantrabs** [comment]
feel like the card height could be slightly shorter

also assuming the hero will be fixed when merged

**Comment by AmirAgassi** [comment]
> feel like the card height could be slightly shorter
> 
> also assuming the hero will be fixed when merged

oh man. checking back in 2 weeks later, these cards are HUGE on my laptop 😭
fixing it now

**Review by juancwu — COMMENTED** [review]
lgtm :+1:

**Review by juancwu — CHANGES_REQUESTED** [review]
so... maybe not lgtm, easy fix tho

image

**Pull request merged**
